/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-component-sources.js from index.ts
 * Run: npm run generate:component-sources
 */

import MantineCardSource from "../../components/Card/MantineCard.tsx?raw";
import MantineButtonSource from "../../components/Button/MantineButton.tsx?raw";
import MantineTextSource from "../../components/Text/MantineText.tsx?raw";
import MantineTitleSource from "../../components/Title/MantineTitle.tsx?raw";
import MantineImageSource from "../../components/Image/MantineImage.tsx?raw";
import MantineLinkSource from "../../components/Link/MantineLink.tsx?raw";
import MantineAvatarSource from "../../components/Avatar/MantineAvatar.tsx?raw";
import MantineSectionSource from "../../components/Section/MantineSection.tsx?raw";
import ButtonGroupSource from "../../components/Button/ButtonGroup.tsx?raw";
import MantineMarkdownSource from "../../components/Markdown/MantineMarkdown.tsx?raw";
import MantineInputSource from "../../components/Input/MantineInput.tsx?raw";
import MantineBadgeSource from "../../components/Badge/MantineBadge.tsx?raw";
import MantineModalSource from "../../components/Modal/MantineModal.tsx?raw";
import MantineAlertSource from "../../components/Alert/MantineAlert.tsx?raw";
import TabsSource from "../../components/Tabs/Tabs.tsx?raw";
import MantineAccordionSource from "../../components/Accordion/MantineAccordion.tsx?raw";
import MantineIconSource from "../../components/Icon/MantineIcon.tsx?raw";
import MantineGridSource from "../../components/Grid/MantineGrid.tsx?raw";

export const componentSourceMap: Record<string, string> = {
  MantineCard: MantineCardSource,
  MantineButton: MantineButtonSource,
  MantineText: MantineTextSource,
  MantineTitle: MantineTitleSource,
  MantineImage: MantineImageSource,
  MantineLink: MantineLinkSource,
  MantineAvatar: MantineAvatarSource,
  MantineSection: MantineSectionSource,
  ButtonGroup: ButtonGroupSource,
  MantineMarkdown: MantineMarkdownSource,
  MantineInput: MantineInputSource,
  MantineBadge: MantineBadgeSource,
  MantineModal: MantineModalSource,
  MantineAlert: MantineAlertSource,
  Tabs: TabsSource,
  MantineAccordion: MantineAccordionSource,
  MantineIcon: MantineIconSource,
  MantineGrid: MantineGridSource,
};
