/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generate-component-sources.js from index.ts
 * Run: npm run generate:component-sources
 */

import MantineCardSource from "../Card/MantineCard.tsx?raw";
import MantineButtonSource from "../Button/MantineButton.tsx?raw";
import MantineTextSource from "../Text/MantineText.tsx?raw";
import MantineTitleSource from "../Title/MantineTitle.tsx?raw";
import MantineImageSource from "../Image/MantineImage.tsx?raw";
import MantineLinkSource from "../Link/MantineLink.tsx?raw";
import MantineAvatarSource from "../Avatar/MantineAvatar.tsx?raw";
import MantineSectionSource from "../Section/MantineSection.tsx?raw";
import ButtonGroupSource from "../Button/ButtonGroup.tsx?raw";
import MantineMarkdownSource from "../Markdown/MantineMarkdown.tsx?raw";
import MantineInputSource from "../Input/MantineInput.tsx?raw";
import MantineBadgeSource from "../Badge/MantineBadge.tsx?raw";
import MantineModalSource from "../Modal/MantineModal.tsx?raw";
import MantineAlertSource from "../Alert/MantineAlert.tsx?raw";
import TabsSource from "../Tabs/Tabs.tsx?raw";
import MantineAccordionSource from "../Accordion/MantineAccordion.tsx?raw";
import MantineIconSource from "../Icon/MantineIcon.tsx?raw";
import MantineGridSource from "../Grid/MantineGrid.tsx?raw";

export const componentSourceMap: Record<string, string> = {
  MantineCard: MantineCardSource,
  MantineButton: MantineButtonSource,
  MantineText: MantineTextSource,
  MantineTitle: MantineTitleSource,
  MantineImage: MantineImageSource,
  MantineLink: MantineLinkSource,
  MantineAvatar: MantineAvatarSource,
  MantineSection: MantineSectionSource,
  ButtonGroup: ButtonGroupSource,
  MantineMarkdown: MantineMarkdownSource,
  MantineInput: MantineInputSource,
  MantineBadge: MantineBadgeSource,
  MantineModal: MantineModalSource,
  MantineAlert: MantineAlertSource,
  Tabs: TabsSource,
  MantineAccordion: MantineAccordionSource,
  MantineIcon: MantineIconSource,
  MantineGrid: MantineGridSource,
};
